[build]
  command = "npm run build"
  publish = "build" # or "dist" if you’re using Vite
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

# Optional: Redirect all routes to index.html (for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
